language: go

go:
  - 1.11.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 0f7fc8a3-741b-4a89-958c-b4a76b40a936
